apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: docker.io/dkalinin/consul-helm-naked
    image:
      url: dkalinin/consul-helm
    excludePaths:
    - .git/**/*

  - path: docker.io/dkalinin/consul-helm-by-tag
    image:
      url: dkalinin/consul-helm:latest
    excludePaths:
    - .git/**/*  

  - path: docker.io/dkalinin/consul-helm-by-digest
    image:
      url: index.docker.io/dkalinin/consul-helm@sha256:d1cdbd46561a144332f0744302d45f27583fc0d75002cba473d840f46630c9f7
    excludePaths:
    - .git/**/*

  - path: tag-selection
    image:
      url: k14stest/vendir-image-tag-selection
      tagSelection:
        semver:
          constraints: ">1.0.0 <3.0.0"
