apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: exact-sha
    hg:
      url: https://hg.sr.ht/~sircmpwn/hg.sr.ht
      ref: 180c776fe29448afa8c756ab572bab7a1cf17a06
    includePaths:
    - scss/main.scss

  - path: tag
    hg:
      url: https://hg.sr.ht/~sircmpwn/hg.sr.ht
      ref: 0.11.0
    includePaths:
    - scss/main.scss
