apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: docker.io/ewrenn/consul-helm-naked
    imgpkgBundle:
      image: ewrenn/consul-helm-bundle
    excludePaths:
    - .git/**/*

  - path: docker.io/ewrenn/consul-helm-by-tag
    imgpkgBundle:
      image: ewrenn/consul-helm-bundle:v1
    excludePaths:
    - .git/**/*

  - path: docker.io/ewrenn/consul-helm-by-digest
    imgpkgBundle:
      image: index.docker.io/ewrenn/consul-helm-bundle@sha256:15777f0007ee10fb9b2e0ed55107751188f3f3a11bae81c122ff4f11c9d67d15
    excludePaths:
    - .git/**/*

  - path: docker.io/k8slt/vendir-test-recursive-bundle
    imgpkgBundle:
      image: index.docker.io/k8slt/vendir-test-recursive-bundle@sha256:4d58d662d3f6e858fb3f989214482405ac13974d98f3f0695bd36e3fc36d3f81
      recursive: true

  - path: tag-selection
    imgpkgBundle:
      image: k14stest/vendir-imgpkgbundle-tag-selection
      tagSelection:
        semver:
          constraints: ">1.0.0 <3.0.0"
